version: '3.8'
services:
  # MySQL Database Service
  mysql-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE:
      MYSQL_USER:
      MYSQL_PASSWORD:
    ports:
      - "3306:3306"
    volumes:
      - ./my-new-data-dir:/var/lib/mysql  # Host-mounted directory for MySQL data
      - ./my-custom-config:/etc/mysql/conf.d
    command: --pid-file=/tmp/mysqld.pid
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: always

  # Spring Boot Application Service
  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_APPLICATION_NAME: ziong
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/ziong_db
      SPRING_DATASOURCE_USERNAME:
      SPRING_DATASOURCE_PASSWORD:
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      SPRING_MAIL_HOST: smtp.hostinger.com
      SPRING_MAIL_USERNAME:
      SPRING_MAIL_PASSWORD:
      SPRING_MAIL_PORT: 465
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH: "true"
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE: "true"
    ports:
      - "443:443"  # Map Spring Boot port to host
    depends_on:
      mysql-db:
        condition: service_healthy
    restart: always
volumes:
  my-new-data-dir:
# Removed the `mysql-data` volume as it is no longer used.
